Block/Adminhtml/Order/View/Items/Renderer/WarrantyRenderer.php
Controller/Adminhtml/Contract/Refund.php
Helper/Api/Data.php
Model/Api/Request/ProductDataBuilder.php
etc/adminhtml/system.xml

Fix to the product’s image URL to send the full URL
Add new setting in admin to enable/disable the request of refunds

Uat 24 06 20

---

Controller/Cart/Add.php
Helper/Api/Data.php
Observer/Warranty/AddToCart.php
Setup/InstallData.php
etc/di.xml

- Catch error when warranty product is not found
- Correct bug for missing method
- Retrieve default attribute set in warranty creation or return error

Uat 14 07 20 

---

Console/Command/SyncProducts.php
ViewModel/Installation.php
view/frontend/templates/installation.phtml

Update testConnection call removal to mitigate performance issues.

Uat 01 09 20

---

Model/Product/Type.php

Fixes Conflict with MageWorx extension, raised by Tool Nut.

Uat 03 09 20 

---

Api/ConnectorInterface.php
Api/SyncInterface.php
Model/Api/Connector.php
Model/Api/Request/ProductDataBuilder.php
Model/Api/Sync/Product/ProductsRequest.php
Model/Product/Sync.php
Model/SyncProcess.php
composer.json

Void/Null return types issues.
Composer file adjustment.

PHP 7 Compatibility

---

view/frontend/templates/cart/item/default.phtml
view/frontend/web/js/cart/addToCart.js

Issues with warranties on configurable products for the cart page.

HEL-319: Cart view fixes.

---

Model/Api/Connector.php
Model/Api/Request/ContractBuilder.php
Model/Api/Request/ProductDataBuilder.php
composer.json
view/frontend/templates/cart/item/default.phtml
view/frontend/web/js/cart/addToCart.js

**Features**
- API Upgrade to Version 2020-08-01
**Bug Fixes** 
- Fix for cart behavior when multiple different configurations have warranties elected in the cart view

Release 100.2.2

---

Helper/Api/Data.php
view/adminhtml/templates/system/config/intro.phtml

Show Magento module version in the Extend Panel.

Show Extend Version in the Extend Panel.

---

etc/csp_whitelist.xml

- add font files added through SDK to CSP whitelist

EX-4 Analytics tracking

---

Controller/Cart/Add.php
Model/Leads.php
Observer/Warranty/AddToCart.php
ViewModel/Installation.php
ViewModel/Warranty.php
etc/config.xml
etc/di.xml
view/adminhtml/templates/installation.phtml
view/adminhtml/templates/system/config/products/button.phtml
view/frontend/layout/catalog_product_view_type_grouped.xml
view/frontend/layout/checkout_cart_item_renderers.xml
view/frontend/templates/cart/item/default.phtml
view/frontend/templates/grouped.phtml
view/frontend/templates/installation.phtml
view/frontend/templates/success.phtml
view/frontend/templates/warranty.phtml
view/frontend/web/js/cart/addToCart.js
view/frontend/web/js/warranties.js

Reverts helloextend/magento-extension#111

Revert "Revert "Origin/ex 164""

---

Observer/RequestRefundObserver.php

 credit memo for multiple warranty line items

---

Helper/Api/Data.php

Resolve store scope issue.

---

Helper/Api/Magento/Data.php
Plugin/Api/OrderItemRepositoryInterfacePlugin.php
Plugin/Api/OrderRepositoryInterfacePlugin.php
etc/webapi_rest/di.xml

Add extend extension attributes to <store_url>/V1/orders request

Add extend extension attributes to <store_url>/V1/orders request

---

Model/Plugin/PriceBackend.php

Fix M2's native Fixed Product Tax feature issue

Fix M2's native Fixed Product Tax feature issue

---

ViewModel/Warranty.php

convert expiration timestamp to seconds

legacy-367

---

Model/Api/Request/ContractBuilder.php
Model/Api/Request/OrderBuilder.php

[M2] - For the Order create API call, pull currency from the following in order of priority: 1) Order -> 2) Store View -> 3) Default Currency

EX-374 Legacy

---

Model/Api/Request/ProductDataBuilder.php

[M2] - Product Sync - Truncate the Description to a maximum of 2,000 charact

EX-371 Legacy

---

Controller/Adminhtml/Contract/Refund.php
Model/Api/Request/ContractBuilder.php
Model/Api/Sync/Contract/ContractsRequest.php
Model/Api/Sync/Lead/LeadsRequest.php
Model/Config/Source/CreateContractApi.php
Model/ContractCreateProcess.php
Model/CreateContract.php
Model/Leads.php
Observer/CreateLead.php
Observer/RequestRefundObserver.php
Setup/Patch/Data/RemoveContractApiConfiguration.bk
Setup/UpgradeData.php
composer.json
etc/config.xml
etc/module.xml

Remove instances of the Contract API and remove any configuration set to use the Contract API

Legacy - 361

---

view/frontend/web/js/product/bundle-warranty.js

- fixed issue when option is optional and none is selected the previously rendered warranty offers wasn't removed
- fixed issue with wrong place rendered offers for radio type of options

[EX-354] [M2] Support for bundled products

---

Plugin/Quote/Model/Item/SetItemDataPlugin.php

- added check for buyRequest variable
- added declaration for $buyRequestValues with default empty array

[EX-407] [M2] errors reported by merchant after going live

---

Block/System/Config/Intro.php
Helper/Api/Data.php
composer.json
etc/config.xml
etc/module.xml
view/adminhtml/templates/system/config/intro.phtml

- updated composer
- added tag version to config.xml
- added support for tag version to extend admin intro

[EX-410] [M2] Implement versioning for M2 extensions

---

ViewModel/Installation.php

- added magento and module version to installation
- added pdp placement support to installation config

[EX-394] [M2] Define Magento Configuration Settings to Reserved "Integration" Namespace on Extend object

---

Block/System/Config/Products/Button.php
Controller/Adminhtml/Products/Sync.php
Controller/Adminhtml/Products/Sync/ResetSyncDate.php
Model/Product/Sync.php
Model/ProductSyncProcess.php
Setup/Patch/Data/RemoveLastSyncValue.php
view/adminhtml/templates/system/config/products/button.phtml
view/adminhtml/web/js/products/sync.js

- removed updating lastSyncDate config value for default scope every sync ran as this value is spreading for child stores which were not synced yet

[EX-439] [M2] Product sync incorrect behavior for products present in multistore

---

view/frontend/web/js/product/simple-warranty.js

- fixes for PDP with related products

[EX-432] [M2-legacy] Warranty Base code doesn't account for method for insertionPoint

---

view/frontend/web/js/product/simple-warranty.js

- fixes for PDP with related products

[EX-432] [M2] Warranty Base code doesn't account for method for insertionPoint

---

Model/Api/Sync/Orders/OrdersRequest.php

- fixed issue, added check for lead token exist in extend response. as not all products has lead token

[EX-445] [M2] exception.log errors upon creating orders in admin

---

Block/System/Config/AbstractSyncButton.php
Block/System/Config/Orders/Button.php
Block/System/Config/Products/Button.php
Controller/Adminhtml/Orders/HistoricalOrders.php
Model/Api/Request/OrderBuilder.php
view/adminhtml/templates/system/config/orders/button.phtml
view/adminhtml/web/js/orders/sync.js

- applied logic to run sync process only store by store instead of global or website scopes
- added message about number of order sync process

[EX-126] [M2] Send historical orders to Orders API

---

Api/ConnectorInterface.php
Controller/Adminhtml/Contract/Refund.php
Model/Api/Connector.php
Model/Api/Response.php
Model/Api/Sync/AbstractRequest.php
Model/Api/Sync/Contract/ContractsRequest.php
Model/Api/Sync/Lead/LeadInfoRequest.php
Model/Api/Sync/Lead/LeadsRequest.php
Model/Api/Sync/Offer/OffersRequest.php
Model/Api/Sync/Orders/HistoricalOrdersRequest.php
Model/Api/Sync/Orders/OrdersRequest.php
Model/Api/Sync/Orders/RefundRequest.php
Model/Api/Sync/Product/ProductsRequest.php
Observer/RequestRefundObserver.php

- refactored Api Client from Zend to cURL
- fixed depersonalizing issue for history orders

[EX-472] [M2] M2.4.6 incompatibility

---

etc/adminhtml/system.xml

[EX-471] [M2] Configuration Labels changes

---

Model/Api/Request/OrderBuilder.php
Model/Api/Request/ProductDataBuilder.php
Model/Api/Sync/Orders/OrdersRequest.php

- added missed fields on order and line item level
- changed logic for product listPrice to follow special price configuration
- added fix for cases when product has not category assigned
- added taxCostTotal for order level when order created
- updated version for API Order Request

Legacy 479

---

ViewModel/Warranty.php
etc/config.xml

brought back a method to ensure compatibility with Extend's Hyva module

Patch Release -  hyva compatibiliy PR

---

view/adminhtml/layout/sales_order_create_load_block_data.xml

Fix for add product by SKU missing on m2 EE

Patch Release - Update sales_order_create_load_block_data.xml

---

view/adminhtml/layout/sales_order_create_index.xml
view/adminhtml/layout/sales_order_create_load_block_data.xml

missing Extend install on refresh in admin orders

Patch Release : admin layout fix for admin create order

---

view/adminhtml/templates/extend-js.phtml

changed script rendering to be compliant with CSP rules in magento 2.4.7

Patch Release : Update extend-js.phtml

---

view/adminhtml/templates/installation.phtml

use securerenderer to be CSP compliant

Patch Release : Update installation.phtml

---

etc/csp_whitelist.xml
view/adminhtml/templates/confirm-modal.phtml
view/adminhtml/templates/items/column/name.phtml
view/adminhtml/templates/order/create/items/warranty.phtml
view/adminhtml/templates/order/view/leads.phtml
view/adminhtml/web/js/contract/refund.js
view/frontend/templates/installation.phtml
view/frontend/templates/tracking/checkout-success.phtml

Patch Release : converted all remaining script tags to to heredoc+securerenderer

---

composer.json

Patch Release : Update composer.json

---

Model/Api/Request/ProductDataBuilder.php

added logic to dynamically build bundle price with their default selections values

Patch Release : Update ProductDataBuilder.php

---

view/adminhtml/templates/order/view/leads.phtml

fix array to string conversion error

Patch Release: Update leads.phtml

---

.github/workflows/changelog_update.yml
.github/workflows/master-changelog_manager.yml

refactor: [DX-3251] - blacksmith runner and cache refactor
[DX-3251]: https://helloextend.atlassian.net/browse/DX-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: [DX-3251] - blacksmith runner and cache refactor

---

.github/workflows/run-migration.yml

Add migration workflow to enable repository migrations via repo-sitioner

ci: [dx-3307] add migration workflow
